# Generated by Django 3.0.7 on 2020-06-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description_short', models.CharField(max_length=255)),
                ('description_long', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
    ]
