# Generated by Django 3.0.7 on 2020-06-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_add_place_photo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placephoto',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.Place'),
        ),
    ]
