# Generated by Django 3.0.7 on 2020-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_change_place_photo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True),
        ),
    ]
