# Generated by Django 3.0.7 on 2020-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_add_slug_for_place_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
