# Generated by Django 3.0.7 on 2020-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_replace_decimal_on_float_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placephoto',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
