# Generated by Django 3.0.7 on 2020-06-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_photo_model_no_required_title_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placephoto',
            options={'ordering': ('order',)},
        ),
    ]
